name: Upload sideboard guides to releases

on: push

jobs:
  release_guides:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/*.pdf
