name: Upload sideboard guides to releases

on: push

jobs:
  release_guides:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile PDFs
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make
      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Sideboard_Guides_$(date +"%Y.%m.%d_%H-%M")"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            out/*.pdf
